# CI/CD pipeline for the coverviz package, does not include build stage
image: python:latest

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - python setup.py install

lint:
  script:
    - ruff ./coverviz ./tests
    - flake8 ./coverviz ./tests
    - pylint ./coverviz ./tests --disable=W0107

type:
  script:
    - mypy ./coverviz

test:
  script:
    - python setup.py install
    - pytest ./tests
