package:
  name: coverviz
  version: 0.0.1

source:
  path: ../coverviz

requirements:
  host:
    - python=3.10
    - setuptools
    - pip

  build:
    - python
    - setuptools
    - path
    - squarify

  run:
    - python

about:
  home: http://github.com/loicdiridollou/coverviz
