package:
  name: coverviz
  version: 0.0.1

source:
  path: ../coverviz

build:
  number: 0
  script: "{{ PYTHON }} setup.py install"

requirements:
  host:
    - python
    - setuptools
    - pip
    - pandas
    - squarify
    - matplotlib
    - seaborn

  run:
    - python
    - pandas>=1.4.4
    - squarify
    - matplotlib
    - seaborn

about:
  home: http://github.com/loicdiridollou/coverviz
