package:
  name: coverviz
  version: 0.0.1

source:
  git_url: https://github.com/loicdiridollou/coverviz.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://github.com/loicdiridollou/coverviz
