name: Linting and testing

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python setup.py install
      - name: Lint with ruff, flake8 and pylint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff ./coverviz
          flake8 ./coverviz          
          pylint ./coverviz

      - name: Type checking with mypy
        run: |
          mypy ./coverviz

      - name: Test with pytest
        run: |
          pytest
